name: Deploy to Amazon ECS

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual deployment'
        required: false
        default: 'Manual deployment'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create SSM Parameters for secrets
      run: |
        # Generate a random app key if it doesn't exist
        if ! aws ssm get-parameter --name /laravel-app/app-key 2>/dev/null; then
          APP_KEY=$(openssl rand -base64 32)
          aws ssm put-parameter \
            --name /laravel-app/app-key \
            --value "base64:$APP_KEY" \
            --type SecureString \
            --overwrite
        fi
        
        # Store database password
        aws ssm put-parameter \
          --name /laravel-app/db-password \
          --value "rootpassword" \
          --type SecureString \
          --overwrite

    - name: Deploy CloudFormation stack
      run: |
        # Set stack name
        AWS_STACK_NAME="laravel-app-stack"
        
        # Check if stack exists and get its status
        if aws cloudformation describe-stacks --stack-name "$AWS_STACK_NAME" &> /dev/null; then
          # Check the current stack status
          CURRENT_STATUS=$(aws cloudformation describe-stacks --stack-name "$AWS_STACK_NAME" --query "Stacks[0].StackStatus" --output text)
          
          echo "Stack exists with status: $CURRENT_STATUS"
          
          if [[ "$CURRENT_STATUS" == "CREATE_COMPLETE" || "$CURRENT_STATUS" == "UPDATE_COMPLETE" || "$CURRENT_STATUS" == "ROLLBACK_COMPLETE" || "$CURRENT_STATUS" == "UPDATE_ROLLBACK_COMPLETE" ]]; then
            # Stack exists and is in a stable state, update it
            echo "Updating existing stack..."
            aws cloudformation update-stack \
              --stack-name "$AWS_STACK_NAME" \
              --template-body file://cloudformation.yml \
              --capabilities CAPABILITY_IAM \
              || echo "No updates to be performed."
          else
            # Stack exists but is in an unstable state, delete it first
            echo "Stack is in state $CURRENT_STATUS. Deleting and recreating..."
            
            # First, get the ECR repository URI
            ECR_REPO=$(aws cloudformation describe-stack-resources \
              --stack-name "$AWS_STACK_NAME" \
              --logical-resource-id ECRRepository \
              --query "StackResources[0].PhysicalResourceId" \
              --output text 2>/dev/null || echo "")
            
            if [ ! -z "$ECR_REPO" ]; then
              echo "Deleting images from ECR repository: $ECR_REPO"
              # Get all image digests
              IMAGE_DIGESTS=$(aws ecr list-images \
                --repository-name "$ECR_REPO" \
                --query 'imageIds[*].imageDigest' \
                --output json 2>/dev/null || echo "[]")
              
              # If there are images, delete them
              if [ "$IMAGE_DIGESTS" != "[]" ]; then
                echo "Deleting images from ECR repository"
                aws ecr batch-delete-image \
                  --repository-name "$ECR_REPO" \
                  --image-ids "$(echo $IMAGE_DIGESTS | jq -r '.[] | {"imageDigest": .} | @json' | jq -s .)" \
                  || echo "Failed to delete images, continuing anyway"
              fi
            fi
            
            # Now delete the stack
            aws cloudformation delete-stack --stack-name "$AWS_STACK_NAME"
            
            # Wait for stack deletion to complete
            echo "Waiting for stack deletion to complete..."
            aws cloudformation wait stack-delete-complete --stack-name "$AWS_STACK_NAME"
            
            # Create new stack
            echo "Creating new stack..."
            aws cloudformation create-stack \
              --stack-name "$AWS_STACK_NAME" \
              --template-body file://cloudformation.yml \
              --capabilities CAPABILITY_IAM
          fi
        else
          # Stack doesn't exist, create it
          echo "Stack does not exist. Creating new stack..."
          aws cloudformation create-stack \
            --stack-name "$AWS_STACK_NAME" \
            --template-body file://cloudformation.yml \
            --capabilities CAPABILITY_IAM
        fi
        
        # Wait for stack creation/update to complete
        echo "Waiting for stack operation to complete..."
        aws cloudformation wait stack-create-complete --stack-name "$AWS_STACK_NAME" || \
        aws cloudformation wait stack-update-complete --stack-name "$AWS_STACK_NAME"
        
        # Get outputs from the stack
        echo "Getting stack outputs..."
        aws cloudformation describe-stacks --stack-name "$AWS_STACK_NAME" --query "Stacks[0].Outputs" --output json

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: laravel-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and push it to ECR
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Update ECS service
      run: |
        aws ecs update-service --cluster laravel-app-cluster --service laravel-app-service --force-new-deployment

    - name: Wait for service to stabilize
      run: |
        aws ecs wait services-stable --cluster laravel-app-cluster --services laravel-app-service

    - name: Get EC2 instance ID
      id: get-instance
      run: |
        # Get the EC2 instance ID from the Auto Scaling Group
        INSTANCE_ID=$(aws autoscaling describe-auto-scaling-groups \
          --auto-scaling-group-names $(aws cloudformation describe-stack-resources \
            --stack-name laravel-app-stack \
            --logical-resource-id ECSAutoScalingGroup \
            --query "StackResources[0].PhysicalResourceId" \
            --output text) \
          --query "AutoScalingGroups[0].Instances[0].InstanceId" \
          --output text)
        echo "::set-output name=instance-id::$INSTANCE_ID"
        echo "EC2 Instance ID: $INSTANCE_ID"

    - name: Run database migrations
      run: |
        # Get the ECS task ARN
        TASK_ARN=$(aws ecs list-tasks \
          --cluster laravel-app-cluster \
          --service-name laravel-app-service \
          --query 'taskArns[0]' \
          --output text)
        
        if [ "$TASK_ARN" != "None" ] && [ ! -z "$TASK_ARN" ]; then
          # Wait a bit for the container to be ready
          echo "Waiting for container to be ready..."
          sleep 30
          
          # Run migrations using ECS Execute Command
          echo "Running database migrations"
          aws ecs execute-command \
            --cluster laravel-app-cluster \
            --task $TASK_ARN \
            --container app \
            --command "/bin/sh -c 'cd /var/www && php artisan migrate --force'" \
            --interactive || echo "Migration command failed, container might not be ready yet"
        else
          echo "No ECS tasks found, skipping migrations"
        fi

    - name: Print application URL
      run: |
        echo "Application deployed successfully!"
        echo "URL: http://$(aws cloudformation describe-stacks \
          --stack-name laravel-app-stack \
          --query "Stacks[0].Outputs[?OutputKey=='LoadBalancerDNS'].OutputValue" \
          --output text)"
        echo "WARNING: Stack will be automatically deleted after 30 minutes to avoid charges!"
